# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
#image: node:8-alpine
image: erikwegner/alpine-node-chromium:20-alpine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - prepare
  - test
  - package
  - betaupload

before_script:
  - node -v
  - npm -v

install:
  stage: prepare
  script: npm install

firefox-package:
  only:
    refs:
      - master
  stage: package
  script: npm run sign:firefox
  artifacts:
    paths:
    - release/firefox/web-ext-artifacts

lint:
  stage: test
  script: npm run lint
  allow_failure: true

mocha:
  stage: test
  script: npm run test:mocha
  allow_failure: true

karma:
  stage: test
  script: npm run test:karma
  allow_failure: true

betaupload:
  only:
    refs:
      - master
  stage: betaupload
  rules:
    - when: manual
  artifacts:
    paths:
    - release/firefox/web-ext-artifacts
  script:
    - mkdir -p ~/.ssh
    - which ssh-agent || ( apk --update add openssh-client )
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cat "$STAGING_PRIVATE_KEY" | ssh-add -
    - scp release/firefox/web-ext-artifacts/*.xpi $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    - ssh-add -D
    - cat "$MANIFEST_PRIVATE_KEY" | ssh-add -
    - ssh -l $DEPLOY_USER $DEPLOY_HOST $DEPLOY_PATH/create-manifest.py
